[package]
name = "rust_testing"
version = "0.1.0"
authors = ["sponges <spongybacon@hotmail.co.uk>"]

[dependencies]
hyper = "0.10.12"
tokio-core = "0.1"
futures = "0.1.14"
byteorder = "1.0.0"
base64 = "0.6.0"
serde = "1.0.2"
serde_json = "1.0.2"